language: python
python:
  - "3.3"
# command to install dependencies
install:
  - pip install flake8==2.4.1
  - pip install pep257==0.7.0
# command to run tests
script:
  - flake8 . --max-line-length=120
  - pep257 . --ignore=D202,D211
